services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=myadmin
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge